services:
  container1:
    build:
      context: ../Part4_5/.
      dockerfile: Dockerfile
    networks:
      - container1_network
  container2:
    image: nginx:stable
    ports:
      - "80:8080"
    volumes:
      - ./nginx/my_nginx.conf:/etc/nginx/nginx.conf
    networks:
      - container1_network


networks:
  container1_network:
    driver: bridge
